AddEventHandler("es:firstSpawn", function(source)
  TriggerClientEvent('chatMessage', source, 'uGamers', {255, 0, 0}, "^4• Bienvenido a ^0uGamers.CLUB")
  TriggerClientEvent('chatMessage', source, 'uGamers', {255, 0, 0}, "^4• Ingresa al teamspeak: ^0ts3.mancos.club")
  TriggerClientEvent('chatMessage', source, 'uGamers', {255, 0, 0}, "^4• Recuerda seguir las normas de la comunidad.")
  TriggerClientEvent('chatMessage', source, 'uGamers', {255, 0, 0}, "^4• Utiliza ^0/ayuda^4 para ver la lista de comandos.")
end)
